### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [tinelix/irc-client-for-android#3]
I see all your APKs use the same `versionCode`: `1`. Android uses `versionCode` to tell versions apart – `versionName` is just for "human-readable display". Could you please increase `versionCode` with each new tag/release, so updates will be signaled to users having the app installed?

Speaking of updates: I've just [added your app](https://apt.izzysoft.de/fdroid/index/apk/dev.tinelix.irc.android) to my repo, to make it easier to discover and kept up-to-date on users' devices. If you want to have the listing adjusted (descriptions, screenshots etc), just let me know :wink:

**Comment by tretdm** [comment]
until the nads reach, but maybe i will

**Comment by tretdm** [comment]
so, i changed `versionCode` number. 0.3.3 release with `versionCode 20` published.

![SCR_20220502_170236_studio64](https://user-images.githubusercontent.com/76806170/166219893-6aac9919-499a-49fb-823c-43ab40f7d749.png)

**Comment by IzzySoft** [comment]
Thanks! Was picked up fine by my updater \o/
