### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [tinelix/irc-client-for-android#9]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using an expired debug key ("denyAfter 2019-01-01"). As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
@tretdm Any chance? Or did you abandon development of this app?

**Comment by IzzySoft** [comment]
@tretdm I see you are quite occupied "elsewhere" and have no time to attend this. If you plan to in near time, please leave a comment here. If there's no chance to fix this, I'll have to remove your app from my repo in a week. Thanks for understanding!

**Comment by IzzySoft** [comment]
It's been 4 weeks now and not even a single response, so I must assume this issue won't be fixed – and thus have to remove the app from my repo. Sad, given how few IRC clients exist for Android, but cannot be helped then.

I'll leave this issue open for the case you return to this project. Be welcome to reach out to me should you have a fixed release available, so I can re-establish the listing.

**Comment by tretdm** [comment]
I apologize for the huge delay. Unfortunately, the application will have to be completely rewritten; now there is simply no desire to do this, as well as solve problems.

**Comment by tretdm** [comment]
Perhaps I will somehow get around to replacing the certificate, but for now this is my situation.
